# Generated by Django 5.1.6 on 2025-02-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('employer', 'Employer'), ('admin', 'Admin'), ('faculty', 'Faculty')], default='student', max_length=20),
        ),
    ]
