# Generated by Django 5.1.6 on 2025-02-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobpost_employer_alter_jobpost_job_type_and_more'),
        ('users', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
    ]
