# Generated by Django 5.1.6 on 2025-04-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobpost_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback from the employer about this application', null=True),
        ),
    ]
