# Generated by Django 5.1.6 on 2025-02-26 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('faculty_users', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'faculty'}, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
