# Generated by Django 5.1.6 on 2025-02-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_users',
        ),
    ]
